dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
