dependencies {
    implementation 'org.springframework.cloud:spring-cloud-config-server'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
    
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
